import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>#index - lukasnehrke</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="mx-auto flex max-w-4xl items-center justify-between pt-8">
        <h1 className="font-semibold">
          <Link href="/">[ lukasnehrke ]</Link>
        </h1>
        <nav className="flex space-x-4 text-sm text-indigo-600">
          <Link href="#">Projects</Link>
          <Link href="#">Contact</Link>
          <Link href="#">GPG</Link>
        </nav>
      </header>
    </>
  );
}
