name: Playwright Tests

on:
  deployment_status:

jobs:
  run-tests:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install && bunx playwright install --with-deps

      - name: Run tests
        run: bunx playwright test
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}
